version: build.{build}.branch.{branch}
image: Visual Studio 2019

environment:
  matrix:
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    - TOXENV: py310

build: off

install:
  - py -3.7 -m pip install wheel tox

test_script:
  - py -3.7 -m tox

branches:
  except:
    - /doc/
