version: build.{build}.branch.{branch}
image: Visual Studio 2019

environment:
  matrix:
    # - TOXENV: py37-pyyaml
    # - TOXENV: py37-ruamel
    # - TOXENV: py38-pyyaml
    # - TOXENV: py38-ruamel
    # - TOXENV: py39-pyyaml
    # - TOXENV: py39-ruamel
    # - TOXENV: py310-pyyaml
    # - TOXENV: py310-ruamel
    - job_name: dist

branches:
  except:
    - /docs/

for:
  -
    matrix:
      only:
        - TOXENV: py37-ruamel
        - TOXENV: py38-pyyaml
        - TOXENV: py38-ruamel
        - TOXENV: py39-pyyaml
        - TOXENV: py39-ruamel
        - TOXENV: py310-pyyaml
    skip_non_tags: true
  
  -
    matrix:
      only:
        - job_name: dist
    # skip_non_tags: true
    install:
      - py -3.7 -m pip install -U pip build twine wheel
    build: script
    build_script:
      - py -3.7 -m build -o dist
    test_script:
      - ps: py -3.7 -m twine check (Resolve-Path 'dist\*').Path
      - ps: py -3.7 -m pip install (Resolve-Path 'dist\*.whl').Path pytest numpy pandas --no-warn-script-location
      - py -3.7 -m pytest
    artifacts:
      path: 'dist\*'

build: off

install:
  - py -3.7 -m pip install -U pip wheel setuptools
  - py -3.7 -m pip install -U tox

test_script:
  - py -3.7 -m tox
