# Copyright 2021 Sean Robertson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Utilities for (de)serializing Parameterized objects"""

from ._classic_serialization import (
    DEFAULT_BACKUP_DESERIALIZER,
    DEFAULT_BACKUP_SERIALIZER,
    DEFAULT_DESERIALIZER_DICT,
    DEFAULT_SERIALIZER_DICT,
    DefaultArrayDeserializer,
    DefaultArraySerializer,
    DefaultBooleanDeserializer,
    DefaultClassSelectorDeserializer,
    DefaultClassSelectorSerializer,
    DefaultDataFrameDeserializer,
    DefaultDataFrameSerializer,
    DefaultDateDeserializer,
    DefaultDateRangeDeserializer,
    DefaultDateRangeSerializer,
    DefaultDateSerializer,
    DefaultDeserializer,
    DefaultIntegerDeserializer,
    DefaultListDeserializer,
    DefaultListSelectorDeserializer,
    DefaultListSelectorSerializer,
    DefaultNumberDeserializer,
    DefaultNumericTupleDeserializer,
    DefaultObjectSelectorDeserializer,
    DefaultObjectSelectorSerializer,
    DefaultSerializer,
    DefaultSeriesSerializer,
    DefaultStringDeserializer,
    DefaultTupleSerializer,
    deserialize_from_dict,
    deserialize_from_ini,
    deserialize_from_json,
    deserialize_from_yaml,
    JSON_STRING_DESERIALIZER_DICT,
    JSON_STRING_SERIALIZER_DICT,
    JsonStringArrayDeserializer,
    JsonStringArraySerializer,
    JsonStringDataFrameDeserializer,
    JsonStringDataFrameSerializer,
    JsonStringDateRangeDeserializer,
    JsonStringDateRangeSerializer,
    JsonStringDictDeserializer,
    JsonStringDictSerializer,
    JsonStringListDeserializer,
    JsonStringListSelectorDeserializer,
    JsonStringListSelectorSerializer,
    JsonStringListSerializer,
    JsonStringNumericTupleDeserializer,
    JsonStringSeriesDeserializer,
    JsonStringSeriesSerializer,
    JsonStringTupleDeserializer,
    JsonStringTupleSerializer,
    ParamConfigDeserializer,
    ParamConfigSerializer,
    ParamConfigTypeError,
    serialize_to_dict,
    serialize_to_ini,
    serialize_to_json,
    serialize_to_yaml,
)
from ._serializer import (
    JsonSerializable,
    RecklessJsonSerialization,
    RecklessYamlSerialization,
    register_serializer,
    Serializable,
    SerializableSerialization,
    unregister_serializer,
    YamlSerializable,
    YamlSerialization,
)
from ._file_serialization import (
    deserialize_from_json_to_obj,
    deserialize_from_yaml_to_obj,
    serialize_from_obj_to_json,
    serialize_from_obj_to_yaml,
)
from .config import YAML_MODULE_PRIORITIES  # deprecated

__all__ = [
    "DEFAULT_BACKUP_DESERIALIZER",
    "DEFAULT_BACKUP_SERIALIZER",
    "DEFAULT_DESERIALIZER_DICT",
    "DEFAULT_SERIALIZER_DICT",
    "DefaultArrayDeserializer",
    "DefaultArraySerializer",
    "DefaultBooleanDeserializer",
    "DefaultClassSelectorDeserializer",
    "DefaultClassSelectorSerializer",
    "DefaultDataFrameDeserializer",
    "DefaultDataFrameSerializer",
    "DefaultDateDeserializer",
    "DefaultDateRangeDeserializer",
    "DefaultDateRangeSerializer",
    "DefaultDateSerializer",
    "DefaultDeserializer",
    "DefaultIntegerDeserializer",
    "DefaultListDeserializer",
    "DefaultListSelectorDeserializer",
    "DefaultListSelectorSerializer",
    "DefaultNumberDeserializer",
    "DefaultNumericTupleDeserializer",
    "DefaultObjectSelectorDeserializer",
    "DefaultObjectSelectorSerializer",
    "DefaultSerializer",
    "DefaultSeriesSerializer",
    "DefaultStringDeserializer",
    "DefaultTupleSerializer",
    "deserialize_from_dict",
    "deserialize_from_ini",
    "deserialize_from_json_to_obj",
    "deserialize_from_json",
    "deserialize_from_yaml_to_obj",
    "deserialize_from_yaml",
    "JSON_STRING_DESERIALIZER_DICT",
    "JSON_STRING_SERIALIZER_DICT",
    "JsonSerializable",
    "JsonStringArrayDeserializer",
    "JsonStringArraySerializer",
    "JsonStringDataFrameDeserializer",
    "JsonStringDataFrameSerializer",
    "JsonStringDateRangeDeserializer",
    "JsonStringDateRangeSerializer",
    "JsonStringDictDeserializer",
    "JsonStringDictSerializer",
    "JsonStringListDeserializer",
    "JsonStringListSelectorDeserializer",
    "JsonStringListSelectorSerializer",
    "JsonStringListSerializer",
    "JsonStringNumericTupleDeserializer",
    "JsonStringSeriesDeserializer",
    "JsonStringSeriesSerializer",
    "JsonStringTupleDeserializer",
    "JsonStringTupleSerializer",
    "ParamConfigDeserializer",
    "ParamConfigSerializer",
    "ParamConfigTypeError",
    "RecklessJsonSerialization",
    "RecklessYamlSerialization",
    "register_serializer",
    "Serializable",
    "SerializableSerialization",
    "serialize_from_obj_to_json",
    "serialize_from_obj_to_yaml",
    "serialize_to_dict",
    "serialize_to_ini",
    "serialize_to_json",
    "serialize_to_yaml",
    "unregister_serializer",
    "YamlSerializable",
    "YamlSerialization",
]
